name = "swagger-stripe-checkout"
main = "src/index.js"
compatibility_date = "2026-08-10"
preview_urls = false

[vars]
TROUBLE_ALBUM_PRICE_ID = "price_1U84hcCcCCf0OHijzrIcVUxC"
THE_GRAVE_CD_PRICE_ID = "price_1U84gjCcCCf0OHij9XMIkBhV"
THE_GRAVE_ALBUM_PRICE_ID = "price_1U84v0CcCCf0OHijI8N9hc9T"
America_Land_CD_Price_ID = "price_1U84h4CcCCf0OHijl0AoJSaT"
America_Land_Album_Price_ID = "price_1U84hYCcCCf0OHijFIDTLytY"
Gypsy_Road_CD_Price_ID = "price_1U84hECcCCf0OHijyAHXV2FI"
Gypsy_Road_Album_Price_ID = "price_1U84hTCcCCf0OHij4vBOFxpY"

[[r2_buckets]]
binding = "DOWNLOADS_BUCKET"
bucket_name = "swagger-paid-downloads"

[observability]
enabled = true

# Set with: npx wrangler secret put STRIPE_SECRET_KEY
